#!/usr/bin/env bash 
for x in gawk lua5.3 ispell; do 
  command -v $x > /dev/null || sudo apt install $x; done

,h() {  ## ,h              ;  show help
  echo ""
  gawk 'BEGIN        {FS="[(][)][:space:]*[^#]+##[:space:]*"}
        /^,/ && /##/ {printf("%-7s :%s\n",$1,$2) }' , ; }

,gp() {  ## ,gp             ;  commit all, push to github 
   git commit -am saving; git push; git status; }

,lua() {  ## ,lua file       ;  run lua. 
   f=$1; shift
   lua $f.lua $*; }

,snips() { ## ,snips file.md  ;  insert snips from code into markdown
  if  [[ -f "$1" ]]
  then 
    gawk 'function trim(s) {sub(/^[ \t\n]*/,"",s); sub(/[ \t\n]*$/,"",s); return s}

    PASS==1 && /^##/      { k="<"FILENAME" "$2">"    ; next     }
    PASS==1               { SNIP[k] = SNIP[k] sep $0 ; sep="\n" }
    PASS==2               { print }
    PASS==2 && /```julia/ { k=$2" "$3   
                            print(trim(SNIP[k]),"\n```")
                            USED[k]++
                            while(getline x >0) if (x ~ /^```/) break } 
    END { for(k in SNIP)
            if (USED[k] != 1) {
              print("?? used "(USED[k]+0)" time(s) "k)>"/dev/stderr" } }
    ' PASS=1 *.lua PASS=2 $1 > _tmp
    mv _tmp $1 
  else 
    echo "missing $1.md or gawk"
  fi ; }

,spell() { ## ,spell file.md  ;  spell check file
  ispell -x $1 ; }
  
_hello() {
  clear; tput bold; tput setaf 6; cat <<'EOF'
::::::          
'####:   
 ####:   "Life is a series of commas,       
. ##::           not periods."
'##:::
..::::

EOF
  tput sgr0
}

here() { cd $1; basename `pwd`; }    

if  [ -z "$COMMA" ]; then
  _hello
  PROMPT_COMMAND='echo -ne "💫 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'     
  COMMA=1 
fi