#!/usr/bin/env bash 
for x in gawk lua5.3 ispell; do 
  command -v $x > /dev/null || sudo apt install $x; done

_g() { _gp; }
_h() { _help; }
_l() { _lua $*; }
_s() { _snips $*; }

_help() {  ## _h          ;  show help
  echo ""
  gawk 'BEGIN        {FS="[(][)][:space:]*[^#]+##[:space:]*"}
        /^_/ && /##/ {printf("%-7s :%s\n",$1,$2) }' _ ; }

_gp() {  ## _g          ;  commit all, push to github 
   git commit -am saving; git push; git status; }

_lua() {  ## _l file     ;  run lua. 
   f=$1; shift
   lua $f.lua $*; }

_snips() { ## _s file.md  ;  insert snips from code into markdown
  if  [[ -f "$1" ]]
  then 
    gawk 'function trim(s) {sub(/^[ \t\n]*/,"",s); sub(/[ \t\n]*$/,"",s); return s}

    PASS==1 && /^##/      { k="<"FILENAME" "$2">"    ; next     }
    PASS==1               { SNIP[k] = SNIP[k] sep $0 ; sep="\n" }
    PASS==2               { print }
    PASS==2 && /```julia/ { k=$2" "$3   
                            print(trim(SNIP[k]),"\n```")
                            USED[k]++
                            while(getline x >0) if (x ~ /^```/) break } 
    END { for(k in SNIP)
            if (USED[k] != 1) {
              print("?? used "(USED[k]+0)" time(s) "k)>"/dev/stderr" } }
    ' PASS=1 *.lua PASS=2 $1 > _tmp
    mv _tmp $1 
  else 
    echo "missing $1.md or gawk"
  fi ; }

_spell() { ## _spell file.md  ;  spell check file
  ispell -x $1 ; }
  