#!/usr/bin/env bash

    mkdir -p ~/tmp
    echo "pdf-ing $1 ... "
    a2ps                 \
        -Br                 \
        --chars-per-line 105  \
        --file-align=fill      \
        --line-numbers=1        \
        --borders=no             \
        --pro=color               \
        --pretty-print="../etc/lua.ssh" \
        --columns  3                 \
        -M letter                     \
        -o     ~/tmp/$1.ps $1.lua
    ps2pdf ~/tmp/$1.ps ~/tmp/$1.pdf; rm ~/tmp/$1.ps
    open ~/tmp/$1.pdf

